<a href="https://colab.research.google.com/github/KOUSHIKEYA-VADIKA/ML-Learning/blob/main/Handling_imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imbalanced dataset:
A dataset with an unequal class distribution

In [ ]:
#importing the dependencies
import numpy as np
import pandas as pd

In [ ]:
#loading the dataset to pandas df
credit_card_data = pd.read_csv('/credit_data.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
75352,56019,-0.330203,1.265306,0.703968,0.943073,0.020692,-0.334221,0.406527,0.313829,-0.924290,...,0.222834,0.653481,-0.024697,0.123168,-0.154517,-0.303343,-0.020581,-0.017914,17.45,0.0
75353,56020,-0.824159,0.689632,0.238364,0.843827,-1.723679,2.003802,3.194546,-0.727345,-0.680086,...,-0.092779,0.491220,-0.376126,-0.768536,-0.152191,-0.255962,0.014022,-0.227837,570.00,0.0
75354,56020,0.929735,-0.299633,0.394750,0.540756,0.272645,1.656454,-0.410577,0.600046,0.184701,...,-0.038120,0.102605,0.094452,-0.985089,0.094890,0.376660,0.038140,-0.005591,44.43,0.0
75355,56021,-1.657683,-0.426294,1.687198,-1.454421,-2.383477,1.305648,0.658390,0.543973,-1.068176,...,0.166907,0.460901,-0.059376,0.079649,0.353229,-0.323458,0.023944,-0.176926,375.01,0.0
75356,56021,-1.711121,-0.369377,1.440787,0.136071,0.517265,0.196718,-0.006951,0.325528,-1.817459,...,-0.365864,-0.524456,0.085383,-0.342706,0.281718,-0.280851,NaN,NaN,NaN,NaN

In [ ]:
#distribution of the two classes
credit_card_data['Class'].value_counts()

Class
0.0    75173
1.0      183
Name: count, dtype: int64

0 --> correct transaction

1--> fraud

highly imbalanced dataset

In [ ]:
#separating the legit and fraudalent trasactions
legit=credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(75173, 31)
(183, 31)

Under-sampling technique

Building a sample dataset containing similar distribution of Legit and Fraud trasaction

Number of Fraudlent transactions -->492

In [ ]:
legit_sample = legit.sample(n=183, random_state=2)

In [ ]:
legit_sample.shape

(492, 31)

Concatenate Two Dataframes

In [ ]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
31885,36551,1.164296,-0.650955,1.207071,0.759375,-1.506441,-0.229023,-0.879210,0.056356,-0.321754,...,-0.356822,-0.562984,0.041749,0.319486,0.237082,-0.400505,0.079184,0.052298,64.00,0.0
32418,36793,1.407081,-1.077470,0.341091,-1.388730,-1.584060,-1.007906,-0.828052,-0.084183,-2.097511,...,-0.580214,-1.559838,0.295804,0.411200,-0.037092,-0.669992,-0.002577,0.018780,45.95,0.0
20640,31176,-3.460054,-2.899297,-0.950393,0.391218,-0.334604,0.266852,2.776791,-0.542521,0.202322,...,-0.217795,0.168590,0.117755,-0.487867,-0.220430,0.418861,1.271990,-0.104923,946.61,0.0
38212,39295,1.070397,-0.085386,1.379282,1.218171,-0.820606,0.470022,-0.739648,0.357510,0.597059,...,0.026174,0.307109,0.044234,0.224770,0.292002,-0.408443,0.088063,0.025323,0.01,0.0
56671,47533,-1.957885,0.242476,0.320998,3.152519,-0.182063,0.207903,1.403145,-0.074821,-1.435028,...,-0.374985,-0.726270,-0.384311,0.103491,-0.740524,-0.132872,0.286136,-0.476901,301.27,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
73784,55279,-5.753852,0.577610,-6.312782,5.159401,-1.698320,-2.683286,-7.934389,2.373550,-3.073079,...,1.177852,0.175331,-1.211123,-0.446891,-0.405520,-0.165797,1.505516,0.359492,1.00,1.0
73857,55311,-6.159607,1.468713,-6.850888,5.174706,-2.986704,-1.795054,-6.545072,2.621236,-3.605870,...,1.061314,0.125737,0.589592,-0.568731,0.582825,-0.042583,0.951130,0.158996,0.83,1.0
74496,55614,-7.347955,2.397041,-7.572356,5.177819,-2.854838,-1.795239,-8.783235,0.437157,-3.740598,...,-0.175273,0.543325,-0.547955,-0.503722,-0.310933,-0.163986,1.197895,0.378187,0.83,1.0
74507,55618,-7.427924,2.948209,-8.678550,5.185303,-4.761090,-0.957095,-7.773380,0.717309,-3.682359,...,-0.299847,0.610479,0.789023,-0.564512,0.201196,-0.111225,1.144599,0.102280,130.44,1.0
74794,55760,-6.003422,-3.930731,-0.007045,1.714669,3.414667,-2.329583,-1.901512,-2.746111,0.887673,...,1.101671,-0.992494,-0.698259,0.139898,-0.205151,-0.472412,1.775378,-0.104285,311.91,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    183
1.0    183
Name: count, dtype: int64

In [ ]:
#In this way you can balance the dataset